resources:
- namespace-quick.yaml
- hello.yaml
- hello-quick.yaml
- shared/fvm-carbonado-1-p1-quick.yaml
- shared/fvm-carbonado-jan-9-quick.yaml
- jimpick/fvm-sapphire-patch-1.yaml
- jimpick/fvm-sapphire-patch-1-quick.yaml
- jimpick/fvm-carbonado-1.yaml
- jimpick/fvm-carbonado-1-quick.yaml
- jimpick/fvm-carbonado-1-p1-quick.yaml
- BlocksOnAChain/fvm-sapphire-patch-1.yaml
- BlocksOnAChain/fvm-sapphire-patch-1-quick.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
